app.controller("logout",function($http)
{
    //localStorage.removeItem('token');
    $http.get("https://localhost:44350/api/logout")
    .then(function(rsp)
    {
        localStorage.removeItem("token");
    },function(err){
        console.log(err);
    });
});